/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type PriceChangeStruct = {
  price: BigNumberish;
  rate: BigNumberish;
  startTimestamp: BigNumberish;
  index: BigNumberish;
};

export type PriceChangeStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  number
] & {
  price: BigNumber;
  rate: BigNumber;
  startTimestamp: BigNumber;
  index: number;
};

export type ProofStruct = { keyContract: string; pcs: PriceChangeStruct[] };

export type ProofStructOutput = [string, PriceChangeStructOutput[]] & {
  keyContract: string;
  pcs: PriceChangeStructOutput[];
};

export interface SubscriptionKeysInterface extends utils.Interface {
  functions: {
    "balanceOf(address)": FunctionFragment;
    "buyShares(uint256,(address,(uint256,uint128,uint112,uint16)[])[])": FunctionFragment;
    "decreaseSubscriptionPool(uint256,uint256)": FunctionFragment;
    "getBuyPrice(uint256)": FunctionFragment;
    "getCurrentPrice()": FunctionFragment;
    "getLastTraderPriceIndex(address)": FunctionFragment;
    "getPrice(uint256,uint256)": FunctionFragment;
    "getSellPrice(uint256)": FunctionFragment;
    "getKeySubject()": FunctionFragment;
    "getStartHash(address)": FunctionFragment;
    "getSupply()": FunctionFragment;
    "getTaxPrice(uint256)": FunctionFragment;
    "increaseSubscriptionPool(uint256,uint256)": FunctionFragment;
    "sellShares(uint256)": FunctionFragment;
    "verifyHash(bytes32,address)": FunctionFragment;
    "withdrawDeposit()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "balanceOf"
      | "buyShares"
      | "decreaseSubscriptionPool"
      | "getBuyPrice"
      | "getCurrentPrice"
      | "getLastTraderPriceIndex"
      | "getPrice"
      | "getSellPrice"
      | "getKeySubject"
      | "getStartHash"
      | "getSupply"
      | "getTaxPrice"
      | "increaseSubscriptionPool"
      | "sellShares"
      | "verifyHash"
      | "withdrawDeposit"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "buyShares",
    values: [BigNumberish, ProofStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseSubscriptionPool",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastTraderPriceIndex",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getKeySubject",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStartHash",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getSupply", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTaxPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseSubscriptionPool",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDeposit",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseSubscriptionPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastTraderPriceIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKeySubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStartHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSupply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaxPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseSubscriptionPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDeposit",
    data: BytesLike
  ): Result;

  events: {
    "Trade(address,address,bool,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Trade"): EventFragment;
}

export interface TradeEventObject {
  trader: string;
  subject: string;
  isBuy: boolean;
  shareAmount: BigNumber;
  ethAmount: BigNumber;
  supply: BigNumber;
}
export type TradeEvent = TypedEvent<
  [string, string, boolean, BigNumber, BigNumber, BigNumber],
  TradeEventObject
>;

export type TradeEventFilter = TypedEventFilter<TradeEvent>;

export interface SubscriptionKeys extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SubscriptionKeysInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balanceOf(addr: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    buyShares(
      amount: BigNumberish,
      proofs: ProofStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    decreaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBuyPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCurrentPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLastTraderPriceIndex(
      trader: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPrice(
      _supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSellPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getKeySubject(overrides?: CallOverrides): Promise<[string]>;

    getStartHash(trader: string, overrides?: CallOverrides): Promise<[string]>;

    getSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTaxPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    increaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sellShares(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    verifyHash(
      h: BytesLike,
      trader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawDeposit(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  balanceOf(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  buyShares(
    amount: BigNumberish,
    proofs: ProofStruct[],
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  decreaseSubscriptionPool(
    tokenId: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBuyPrice(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCurrentPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getLastTraderPriceIndex(
    trader: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPrice(
    _supply: BigNumberish,
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSellPrice(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getKeySubject(overrides?: CallOverrides): Promise<string>;

  getStartHash(trader: string, overrides?: CallOverrides): Promise<string>;

  getSupply(overrides?: CallOverrides): Promise<BigNumber>;

  getTaxPrice(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  increaseSubscriptionPool(
    tokenId: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sellShares(
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  verifyHash(
    h: BytesLike,
    trader: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawDeposit(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    balanceOf(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyShares(
      amount: BigNumberish,
      proofs: ProofStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    decreaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getBuyPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getLastTraderPriceIndex(
      trader: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      _supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getKeySubject(overrides?: CallOverrides): Promise<string>;

    getStartHash(trader: string, overrides?: CallOverrides): Promise<string>;

    getSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getTaxPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sellShares(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    verifyHash(
      h: BytesLike,
      trader: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    withdrawDeposit(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Trade(address,address,bool,uint256,uint256,uint256)"(
      trader?: null,
      subject?: null,
      isBuy?: null,
      shareAmount?: null,
      ethAmount?: null,
      supply?: null
    ): TradeEventFilter;
    Trade(
      trader?: null,
      subject?: null,
      isBuy?: null,
      shareAmount?: null,
      ethAmount?: null,
      supply?: null
    ): TradeEventFilter;
  };

  estimateGas: {
    balanceOf(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyShares(
      amount: BigNumberish,
      proofs: ProofStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    decreaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBuyPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getLastTraderPriceIndex(
      trader: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      _supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getKeySubject(overrides?: CallOverrides): Promise<BigNumber>;

    getStartHash(trader: string, overrides?: CallOverrides): Promise<BigNumber>;

    getSupply(overrides?: CallOverrides): Promise<BigNumber>;

    getTaxPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sellShares(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    verifyHash(
      h: BytesLike,
      trader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawDeposit(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOf(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyShares(
      amount: BigNumberish,
      proofs: ProofStruct[],
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    decreaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBuyPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastTraderPriceIndex(
      trader: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      _supply: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSellPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getKeySubject(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStartHash(
      trader: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTaxPrice(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseSubscriptionPool(
      tokenId: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sellShares(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    verifyHash(
      h: BytesLike,
      trader: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawDeposit(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
